name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: gitleaks-action with private repo
        uses: actions/checkout@master
        with: 
          repository: spring-media/red-flux-cd
      - name: gitleaks    
        uses: rheien/gitleaks-action@master
